services:
  command-service:
    build: ./src/command-service
    environment:
      NODE_ENV: development
      MARIADB_HOST: mariadb
      MARIADB_USER: root
      MARIADB_PASSWORD: example
      MARIADB_DATABASE: cqrs_db
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    depends_on:
      mariadb:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  query-service:
    build: ./src/query-service
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://mongo:27017/cqrs_db
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  gateway:
    build: ./src/gateway
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      COMMAND_HOST: command-service
      COMMAND_PORT: 3000
      QUERY_HOST: query-service
      QUERY_PORT: 3000
    depends_on:
      - command-service
      - query-service

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: cqrs_db
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: --quiet # Reduce log verbosity

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # RabbitMQ main port
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mariadb_data:
  mongo_data:
