services:
  command-service:
    build: ./src/command-service
    environment:
      NODE_ENV: development
      MARIADB_HOST: mariadb
      MARIADB_USER: root
      MARIADB_PASSWORD: example
      MARIADB_DATABASE: cqrs_db
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    depends_on:
      mariadb:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: cqrs_db
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  query-service-1:
    build: ./src/query-service
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://mongo-1:27017/cqrs_db
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    depends_on:
      mongo-1:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  mongo-1:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_1_data:/data/db
    command: --quiet

  query-service-2:
    build: ./src/query-service
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://mongo-2:27017/cqrs_db
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    depends_on:
      mongo-2:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  mongo-2:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo_2_data:/data/db
    command: --quiet

  query-service-3:
    build: ./src/query-service
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://mongo-3:27017/cqrs_db
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    depends_on:
      mongo-3:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  mongo-3:
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - mongo_3_data:/data/db
    command: --quiet

  nginx:
    image: nginx:latest
    depends_on:
      - query-service-1
      - query-service-2
      - query-service-3
    volumes:
      - ./src/load-balancer/nginx.conf:/etc/nginx/nginx.conf:ro

  gateway:
    build: ./src/gateway
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      COMMAND_HOST: command-service
      COMMAND_PORT: 3000
      QUERY_HOST: nginx
      QUERY_PORT: 80
    depends_on:
      - command-service
      - nginx

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # RabbitMQ main port
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mariadb_data:
  mongo_1_data:
  mongo_2_data:
  mongo_3_data:
